spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/collectiontask?user=root&password=root&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false"
  main:
    banner-mode: off
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
server:
  port: 9002